services:
  db:
    image: postgres:15
    container_name: nest-chavito-project-db
    environment:
      POSTGRES_USER: chavito
      POSTGRES_PASSWORD: chavito
      POSTGRES_DB: chavito
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: nest-chavito-project-app
    command: sh -c "npm run migration:run && npm run start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  db_data:
